### ISSUE TITLE
Need a failing test for negotiateMedia

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Accept#1]
Hi Paul, 

Do you have a failing test, so I can test 

``` php
$media = $this->accept->negotiateMedia($available);
if (! $media) {
   $this->response->status->set(406);
   $this->response->content->setType('text/plain');
   $this->response->content->set(implode(',', $available));
   return false;
}
```

**Comment by pmjones** [comment]
Try an empty array for $available.

**Comment by pmjones** [comment]
Also, see `tests/unit/src/MediaTest.php` for providers that result in false.

**Comment by harikt** [comment]
I don't recall why I have not looked or whether I did looked and was looking for something.
