### ISSUE TITLE
AbstractNegotiator Sort Fails

### ISSUE THREAD

**Issue by lf-jeremy** [auraphp/Aura.Accept#13]
The `AbstractNegotiator` class's `sort` strategy has a logic error.

When it places values in buckets, it uses the value from the `getQuality` method, which returns a `float`.

The `float` value gets typecast into an `integer` index, and all values with the same leading digit `Quality` get grouped together and considered equal.

Typecasting the Quality to a string fixes the behavior.

Before:

```php
$bucket[$value->getQuality()][] = $value;
```

After:

```
$bucket[(string)$value->getQuality()][] = $value;
```

Steps to reproduce:

* Provide non-sorted header value

curl -I --header "Accept-Language: fr-CA;q=0.3,en-US;q=0.6,en-CA;q=0.7,en;q=0.4" APP_ENDPOINT

Expected result from `negotiateLanguage()`: `en-CA`
Actual result: `fr-CA`

**Comment by pmjones** [comment]
Send a PR if you can.

**Comment by lf-jeremy** [comment]
Looks like it was fixed by  89fcd9d, I'll update my dependency version. Thanks!

**Comment by harikt** [comment]
ok, so a release is needed.

**Comment by harikt** [comment]
2.2.5 released : https://github.com/auraphp/Aura.Accept/releases/tag/2.2.5 

Hope that helps.

Thank you for reporting.

**Comment by lf-jeremy** [comment]
Great, thanks! Helped me avoid pointing composer at the branch/commit now thanks to the release.
