### ISSUE TITLE
negotiateMedia returns false with wildcard

### ISSUE THREAD

**Issue by brandonsavage** [auraphp/Aura.Accept#2]
Using a wildcard (`*/*`) should return a valid value. negotiateMedia() returns false as though no type matched.

**Comment by pmjones** [comment]
You mean, using a wildcard for the `$available` value?

**Comment by brandonsavage** [comment]
Yes.

**Comment by pmjones** [comment]
See the new [wild-avail](https://github.com/auraphp/Aura.Accept/tree/wild-avail) branch, specifically commit https://github.com/auraphp/Aura.Accept/commit/ffbb3bedebb9769ea2356edd8eee69068a1dbded . If you pass a full wildcard (`*` or `*/*`)  as an available value, the negotiation will succeed with the wildcard as the negotiated value.

**Comment by brandonsavage** [comment]
This should work!
