### ISSUE TITLE
Making set() / add() public

### ISSUE THREAD

**Issue by mattsah** [auraphp/Aura.Accept#4]
The abstract negotiator has a `set()` and `add()` method which would be good to have as public methods so that the negotiator could be instantiated and have the headers supplied independently from the $_SERVER super global, a mock array, and so that negotiators could be used more directly without the factory.

**Comment by harikt** [comment]
Hi @mattsah 

If I understand you, you were basically looking to change the global values passed to `AcceptFactory` .  The `AcceptFactory` is just for convenience . You can instantiate each one separately as you like , eg : 

``` php
$value_factory = new ValueFactory;
$charset_negotiator = new Charset\CharsetNegotiator($value_factory, $server);
```

And the `$server` will be an array of mocks. And it seems `add` and `set` can be made public if needed.

Let me know if I misunderstood you.

**Comment by mattsah** [comment]
Yes, you understand, and I am aware of that possibility, but passing even the $server with mocks seemed like a backwards step.  I don't deal with the SAPI specifics once I'm at that level, my gateway handles all that conversion into the abstracted request, so I was looking to have set() and add() made public so that I could just pass a string directly.

**Comment by harikt** [comment]
ok. Thanks.
