### ISSUE TITLE
Forgot member declaration

### ISSUE THREAD

**Issue by tomkyle** [auraphp/Aura.Accept#6]
see https://scrutinizer-ci.com/g/auraphp/Aura.Accept/issues/develop-2/files/src/AcceptFactory.php?orderField=path&order=asc#inspectioncomment-626597102 (should be easy for contributing beginner like me)

**Comment by pmjones** [comment]
PR! PR! :-)

**Comment by tomkyle** [comment]
Assuming PR means Pull request; I'll do my very best... ;-)

**Comment by pmjones** [comment]
fixed by #7
